### PR TITLE
fixed absented tag and display column of news items on  576 px

### PR DESCRIPTION
**Pull request by sofiiamatsyhin**

### CODE REVIEW

**Comment by KimAT25** [comment]
You fixed issue with bug 1033, but it`s not correct, please see print screen from mockups
image

Please be careful, when fixing bugs, as person who tested not checked what break points should be.
Please revert changes what you made for bug 1031!

**Comment by sofiiamatsyhin** [comment]
> Check my comment
Thank you, fixed

**Comment by mplesha** [comment]
conflicts

**Comment by sofiiamatsyhin** [comment]
Resolved

**Pull request merged**
