### PR TITLE
[Bugfix] #7038 Change date error messages

### PR DESCRIPTION
**Pull request by kovalsofiia1**
[#7038](https://github.com/ita-social-projects/GreenCity/issues/7038)
Знімок екрана 2024-08-29 171836
Знімок екрана 2024-08-29 171858
Знімок екрана 2024-08-29 174800

### CODE REVIEW

**Comment by bzhn** [comment]
Selecting date `29/08/2022` was still giving `Date not correct` error instead of `Past date can't be chosen` because the `Date.parse()` method in JavaScript follows the `ISO 8601` format for date strings, which is `YYYY-MM-DD`. The format `29/08/2022` does not conform to this standard, and hence, `Date.parse()` didn't recognize it as a valid date.

Fixed this with the latest commit.

image

**Review by bzhn — APPROVED** [review]

**Review by dmytro-kryvyi — APPROVED** [review]

**Comment by kovalsofiia1** [comment]
The user is unable to input a date in the DD/MM/YYYY format. Even if no error message is displayed, the form still rejects the value.
Знімок екрана 2024-08-30 101658
Знімок екрана 2024-08-30 101710

**Comment by dmytro-kryvyi** [comment]
Make it readonly so the user can choose from the menu

**Comment by bzhn** [comment]
The MM/DD/YYYYYY prompt does not fit any format option. Perhaps we should remove the hint altogether?

image

image

**Comment by kovalsofiia1** [comment]
image
Changed hint to DD/MM/YYYY

**Comment by kovalsofiia1** [comment]
[Create event] Change date field according to mock up
[#7445](https://github.com/ita-social-projects/GreenCity/issues/7445)


Result:

Знімок екрана 2024-09-12 212356
Знімок екрана 2024-09-12 212402
Знімок екрана 2024-09-12 212411
Знімок екрана 2024-09-12 213917
Знімок екрана 2024-09-12 214052

**Review by hnativlyubomyr — APPROVED** [review]

**Pull request merged**
